# Use uma imagem base do PostgreSQL
FROM postgres:latest

# Defina a variável de ambiente para a senha do banco de dados
ENV POSTGRES_PASSWORD=senha123

# Copie scripts SQL para dentro do contêiner (se necessário)
# COPY ./scripts/ /docker-entrypoint-initdb.d/