version: '3'
services:
  postgres:
    build:
      context: .  # Diretório onde o Dockerfile está localizado
      dockerfile: Dockerfile
    container_name: meu-postgres
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: usuario_do_banco
      POSTGRES_PASSWORD: senha_secreta
    volumes:
      - pg_data:/var/lib/postgresql/data  # Salvar dados em um volume
    ports:
      - "5432:5432"  # Mapear porta do host para porta do contêiner

volumes:
  pg_data:  # Volume para persistência dos dados