version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: qualis
      POSTGRES_USER: root
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./qualis.sql:/docker-entrypoint-initdb.d/qualis.sql

volumes:
  postgres-data: